---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - syngit.io
  resources:
  - remoteusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syngit.io
  resources:
  - remoteusers/finalizers
  verbs:
  - update
- apiGroups:
  - syngit.io
  resources:
  - remoteusers/status
  verbs:
  - get
  - patch
  - update
